import * as vscode from 'vscode';

export class RefactorCodeActionProvider implements vscode.CodeActionProvider {
    public static readonly providedCodeActionKinds = [vscode.CodeActionKind.QuickFix];

    public provideCodeActions(
        document: vscode.TextDocument,
        _range: vscode.Range | vscode.Selection,
        context: vscode.CodeActionContext,
    ): vscode.ProviderResult<(vscode.Command | vscode.CodeAction)[]> {
        // Filter diagnostics generated by our linter
        const linterDiagnostics = context.diagnostics.filter(
            (diagnostic) => diagnostic.source === 'clean-ast-linter',
        );

        if (linterDiagnostics.length === 0) {
            return [];
        }

        const actions: vscode.CodeAction[] = [];

        for (const diagnostic of linterDiagnostics) {
            const action = this.createAIRefactorAction(document, diagnostic);
            actions.push(action);
        }

        return actions;
    }

    private createAIRefactorAction(
        document: vscode.TextDocument,
        diagnostic: vscode.Diagnostic,
    ): vscode.CodeAction {
        const action = new vscode.CodeAction(
            '💡 Refactorizar con IA (Ollama)',
            vscode.CodeActionKind.QuickFix,
        );

        action.command = {
            command: 'clean-ast-linter.refactorWithAI',
            title: 'Refactor with Local AI (Ollama)',
            arguments: [document, diagnostic.range],
        };

        action.diagnostics = [diagnostic];
        action.isPreferred = true;
        return action;
    }
}
